### ISSUE TITLE
Support multiple clusters

### ISSUE THREAD

**Issue by jakobbraun** [exasol/cloudwatch-dashboard-examples#9]
Currently, the cluster name is hardcoded to `MASTER`.

In newer versions of Exasol, this is going to change:
* Default will get renamed
* Multiple clusters might be possible

The dashboard should reflect these changes.
Approach for dynamically showing multiple metrics: https://stackoverflow.com/questions/48443899/cloudwatch-does-not-aggregate-across-dimensions-for-your-custom-metrics

**Comment by redcatbear** [comment]
PM decision: shelved.
